### PR TITLE
#WIP Admin controller spec

### PR DESCRIPTION
**Pull request by katafira**
Fixed tests. We consider this pull request ready for merging.

IMPORTANT NOTE: 
These specs require pull request #5 with the new Devise config to run the test.
@sergio-ocon @delaluzparra

### CODE REVIEW

**Comment by sergio-ocon** [comment]
Refer to the other as:

NOTE: This pull requests depends on #5 

Two other things:
- Label it WIP until is ready to merge

**Comment by alexvkcr** [comment]
Got it! 

Should we take as a rule that even if no more changes are necessary to add to the PR, we have to add WIP if it depends on another PR?

**Comment by alexvkcr** [comment]
Before taking any action, We now see a sing titled 'Some checks haven’t completed yet' and it says:
continuous-integration/travis-ci — Waiting for status to be reported

What should we do about it? We've never seen anything alike

**Comment by sergio-ocon** [comment]
When you do a commit, all tests are run. 
We are using Travis-CI.

This makes it easier for me to see if the changes you make will break any code and allows me to skip those PR that will break the code.
If you want to skip Travis (because you are not ready to merge it), put [ci skip] somewhere in the commit message.

**Comment by alexvkcr** [comment]
I think there is an error with how travis-ci is set up, I checked the log after failing and 
it says 'command not found: rpec'.

Seemingly there's a typo on rspec command.

**Comment by sergio-ocon** [comment]
You can close and open a PR to get Travis running again in these cases

**Comment by sergio-ocon** [comment]
I am merging this PR, but consider that you need to add new use cases. The ones showed here are not enough.
Consider:
- What happens if a non-admin tries to access an admin tab
- What should the admin see.

**Pull request merged**
